apiVersion: v1
kind: Pod
metadata:
  name: translate-pod
spec:
  containers:
  - name: translate
    image: mninoruiz/translate:latest
    command: [ "node", "bergamot-httpserver.js", "80", "1", "0" ]
    ports:
    - containerPort: 80
  restartPolicy: OnFailure