apiVersion: apps/v1
kind: Deployment
metadata:
  name: translate-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
     app: translate
  template:
    metadata:
      labels:
        app: translate
    spec:
      containers:
      - name: translate
        image: mninoruiz/translate:latest
        command: [ "node", "bergamot-httpserver.js", "80", "1", "0" ]
        ports:
        - containerPort: 80