apiVersion: v1
kind: Service
metadata:
  name: translate-svc
spec:
  type: LoadBalancer
  selector:
    app: translate
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080