name: build
on: [push]

jobs:

  Test:
    name: npm tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install deps
        run: npm install --dev
      - name: Test
        run: npm test
