name: build
on: [push]

jobs:

  Test:
    name: npm tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install deps
        run: npm i --package-lock-only
      - name: Test
        run: npm test
  Lint:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - continue-on-error: true
      - name: Lint
        run: npm run lint
        
  Audit:
    name: audit vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install deps
        run: npm install
      - name: Audit
        run: npm audit