name: build
on: [push]

jobs:

  audit:
    name: audit vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install deps
        run: npm i --package-lock-only
      - name: Test
        run: npm test
      - name: Audit
        run: npm audit
