name: build
on: [push]

jobs:

  Test:
    name: npm tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install deps
        run: npm install --dev
      - name: Test
        run: npm test
  
  Lint:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install deps
        run: npm install --dev
      - name: Lint
        run: npm run lint
        continue-on-error: true # code is very dirty
  
  Audit:
    name: audit vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install deps
        run: npm install
      - name: Audit
        run: npm run audit

  ContainerScan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: mninoruiz/translate:latest
      - name: Docker Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v1
        with:
          image: mninoruiz/translate:latest
          dockerfile: ./Dockerfile
          severity_threshold: HIGH
          annotations: true